name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Copy files to deployment directory
      run: |
        cp -R ${{ github.workspace }}/dist/* /docker-config/recepten/
        cp ${{ github.workspace }}/package.json /docker-config/recepten/


    - name: Restart Service
      run: docker compose -f /docker-config/recepten/compose.yml up -d --force-recreate
